name: Generate JSON

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Run convert script
        run: |
          cmake . -Bbuild
          cmake --build build

      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.2
        with:
          tag: continous

      - name: Release JSON
        uses: softprops/action-gh-release@v0.1.5
        with:
          name: "continous-build"
          files: build/*.json
